### ISSUE TITLE
Live refresh not working with files outside of emails directory

### ISSUE THREAD

**Issue by ryanleichty** [resendlabs/react-email#2304]
### Describe the Bug

I saw [the issue and PR](https://github.com/resend/react-email/pull/1510) for this, but it still seems to be an issue. We have our components in `src/components/`. Changes to any of those components does not update the preview. Only changes to the email templates inside of `emails/` causes it to update the preview.

Our folder structure looks like this:

```
my-project
├── emails
└── src/
    └── components
```

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

NA

### To Reproduce

- Run `npm run dev`
- Make a change to a component within `src/components/`
- Check the preview to see if anything updated
- Make a change to an email template with `emails/`
- Check the preview to see if anything updated

### Expected Behavior

I would expect that the preview would automatically pick up the changes and update everything.

**Comment by gabrielmfern** [comment]
Tried reproducing with `react-email@4.0.16` and it works just fine. Can you make a minimal reproduction for this?

**Comment by ryanleichty** [comment]
You can use this https://github.com/ryanleichty/react-email-demo

**Comment by gabrielmfern** [comment]
Okay, so the problems seems to be a duplicate of #1872, which has been fixed and was released todat in `react-email@4.0.17`. But, trying that out on your reproduction, I see that the hot reloading is breaking due to the circular dependencies you have in your project, which are fine and indicate a bug here, looking into fixing and will keep you updated.

**Comment by ryanleichty** [comment]
@gabrielmfern I resolved the circular dependency and installed the latest version and it's working correctly now 👌

**Comment by jxh0414com** [comment]
I'm experiencing a similar but slightly different issue. Hot reload works fine for email templates in the root emails/ directory, but it doesn't work when email templates are organized in subfolders within the emails directory.
For example:

emails/welcome.tsx - hot reload works ✅
emails/user/welcome.tsx - hot reload doesn't work ❌
emails/admin/notifications.tsx - hot reload doesn't work ❌

The templates render correctly, but changes to files in email subfolders don't trigger preview updates. Is subfolder being supported?
Using react-email@4.0.17 (latest).

**Comment by gabrielmfern** [comment]
Should be fixed in [@react-email/preview-server@4.2.8](https://github.com/resend/react-email/releases/tag/@react-email/preview-server%404.2.8)/[react-email@4.2.8](https://github.com/resend/react-email/releases/tag/react-email%404.2.8)

**Comment by AaronLayton** [comment]
Can confirm I am on 4.2.8 and live reload does `not` work still when in sub folders

`/email/templates/account/my-email.tsx`

**Comment by Nikkoro** [comment]
Same issue, still doesn't work for sub folders. Should be reopened

**Comment by austin-dudzik** [comment]
Also reporting the same. Experienced no change with the release of 4.2.8, with templates in all subdirectories still failing to recompile after file changes, unless restarting the dev server. Needs to be re-investigated, please.
