### ISSUE TITLE
Can't use `"type": "module"` with the preview server

### ISSUE THREAD

**Issue by jslno** [resendlabs/react-email#2377]
### Describe the Bug

When trying to preview an email component in `@react-email/preview-server`, I get the following error:

```
Error: The email component at D:\src\emails\mail.tsx does not contain the expected exports

Error:
    at bs (D:\node_modules\.pnpm\@react-email+preview-server@4.2.3_postcss@8.5.6\node_modules\@react-email\preview-server\.next\server\app\preview\[...slug]\page.js:109:79316)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async v (D:\node_modules\.pnpm\@react-email+preview-server@4.2.3_postcss@8.5.6\node_modules\@react-email\preview-server\.next\server\app\preview\[...slug]\page.js:203:145)
    at async y (D:\node_modules\.pnpm\@react-email+preview-server@4.2.3_postcss@8.5.6\node_modules\@react-email\preview-server\.next\server\app\preview\[...slug]\page.js:21:217)
```

The preview server throws the above error and refuses to render the component, even though there is a valid default export.

### Link to the code that reproduces this issue

https://gist.github.com/jslno/c3f043db1834a7dd4dfee4afab3493f1

### To Reproduce

1. Create a new Next.js 15 project.
2. Install `react-email`, `@react-email/preview-server`, and `@react-email/components`.
3. Add the above email component under `src/emails/mail.tsx`.
4. Run `email dev --dir ./src/emails` and open the preview server in the browser.
5. Try to open `mail`.

Versions
`next`: 15.0.1
`react-email`: 4.2.3
`@react-email/preview-server`: 4.2.3
`@react-email/components`: 0.3.1

Windows 11
pnpm 9.6.0

### Expected Behavior

The preview server should load and render the email component without errors.

### What's your node version? (if relevant)

20.7.0

**Comment by jacobgad** [comment]
I'm running into the same issue

**Comment by darklight9811** [comment]
I downgraded to `3.0.6` and it started working

**Comment by darklight9811** [comment]
@jslno found out if you remove `"type": "module"` from your package.json, it works

**Comment by ak5** [comment]
Also running into this, in a situation where I can't remove `"type": "module"`

**Comment by vcode-sh** [comment]
removing `"type": "module"` fix the problem but it's not a solution to me, causing tons of other problems
```
(node:53038) [MODULE_TYPELESS_PACKAGE_JSON] Warning: Module type of file:///prettier.config.js is not specified and it doesn't parse as CommonJS.
Reparsing as ES module because module syntax was detected. This incurs a performance overhead.
To eliminate this warning, add "type": "module" to /package.json.
```

**Comment by maxratajczak** [comment]
Same issue here

**Comment by WoetDev** [comment]
Also having this error with:

- node v22.16.0 running on WSL2
- pnpm@10.13.1
- next@15.4.2
- react-email@4.2.3

I've downgraded react-email to v4.0.8, which is the earliest working version for me.

**Comment by ThomasBnf** [comment]
Same issue

**Comment by frixou89** [comment]
> [@jslno](https://github.com/jslno) found out if you remove `"type": "module"` from your package.json, it works

That worked for me. Thank you!

**Comment by gabrielmfern** [comment]
Should be fixed in react-email@4.2.4/[@react-email/preview-server@4.2.2](https://github.com/resend/react-email/releases/tag/%40react-email%2Fpreview-server%404.2.4)!

**Comment by xmlking** [comment]
still getting error with ` "@react-email/preview-server": "4.2.4",` when   "type": "module", is added to package.json 
I am using turborepo with email module in `pakcakges/email`

<img width="2400" height="1383" alt="Image" src="https://github.com/user-attachments/assets/da725d82-436a-4346-afa9-8dd703436f0a" />

**Comment by roderickhsiao** [comment]
<img width="1209" height="367" alt="Image" src="https://github.com/user-attachments/assets/a9741a88-2660-4e43-b85d-38a065a1745b" />

Seeing a similar issue on running build, not seeing on dev though. We are not having type: module in the config and also confirmed on the latest version 4.2.4.

Same Nextjs version for our app as well (we nested the email template in sub folder)

**Comment by gabrielmfern** [comment]
@xmlking can you share a reproduction for that? The error seems different even though it's the same conditions.

**Comment by roderickhsiao** [comment]
Found out the issue on my report is on circular dependencies. breaking the dependences works. (use `madge`) package can help :)

**Comment by roderickhsiao** [comment]
Actually still having the issue (the void 0 error). 
Initially I thought its circular dependencies issue, but then its not.
It only happens to us when our template is over 8x-ish running on a 16gb CI server when running email build. (bump up node heap as well), feel like its a memory issue but 

The error looks like the imported file/component are not recognized 

```
import { SomeEmail } from '~/emails/_components/my-custom-email';

const FooBar = () => (
    <SomeEmail />
       );

export default FooBar;

```

Error thrown from react-dom is ` <SomeEmail />` 

```
renderWithHooks (../node_modules/.pnpm/react-dom@19.1.1_react@19.1.1/node_modules/react-dom/cjs/react-dom-server.node.production.js:4179:17)\\n at renderElement (../node_modules/.pnpm/react-dom@19.1.1_react@19.1.1/node_modules/react-dom/cjs/react-dom-server.node.production.js:4317:13)\\n at retryNode (../node_modules/.pnpm/react-dom@19.1.1_react@19.1.1/node_modules/react-dom/cjs/react-dom-server.node.production.js:4919:15)\\n at renderNodeDestructive (../node_modules/.pnpm/react-dom@19.1.1_react@19.1.1/node_modules/react-dom/cjs/react-dom-server.node.production.js:4732:6)\\n at renderNode2 (../node_modules/.pnpm/react-dom@19.1.1_react@19.1.1/node_modules/react-dom/cjs/react-dom-server.node.production.js:5177:13)\\n at renderElement (../node_modules/.pnpm/react-dom@19.1.1_react@19.1.1/node_modules/react-dom/cjs/react-dom-server.node.production.js:4561:17)\\n at retryNode (../node_modules/.pnpm/react-dom@19.1.1_react@19.1.1/node_modules/react-dom/cjs/react-dom-server.node.production.js:4919:15)\\n at performWork (../node_modules/.pnpm/react-dom@19.1.1_react@19.1.1/node_modules/react-dom/cjs/react-dom-server.node.production.js:5561:12)\\n at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)"\n' +
```

Still not able to pin point the issue as locally running build or dev all works fine.

Will update if we found anythning

**Comment by gabrielmfern** [comment]
@roderickhsiao does the error go away if not using `"type": "module"`? It does seem like another problem, but one I've seen intermittently come and go

**Comment by roderickhsiao** [comment]
We are not actually using that in our package

**Comment by roderickhsiao** [comment]
We are not actually using that in our package

**Comment by Gregory-Gerard** [comment]
For those still encountering the error "... does not contain the expected exports ...", try deleting the `.react-email-jsx-runtime` folder inside `node_modules` (in a monorepo, it should be in your email package's node_modules).

The fix from #2381 creates a `package.json` with `{"type": "commonjs"}` inside this folder, but only if the folder doesn't already exist. If you're upgrading incrementally, the folder persists from a previous install and the fix is never applied.
